### ISSUE TITLE
LoadConfig issue 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET#35]
This issue is raised in https://forum.groupdocs.com/t/loadconfig-and-the-googleapi-doesn-t-load/10609/7

Hi,
Please find the sample project attached. It cannot be build successfully. Basically the project is an amended version of this [web forms](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET/tree/master/Demos/WebForms) project. 
Could you please take a look?

Thanks 
[EditorDemoApp.zip](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET/files/7833480/EditorDemoApp.zip)
![loadconfig error 3](https://user-images.githubusercontent.com/15940608/148650286-b4f91f44-e598-47ef-a1e9-374c4219fcd2.PNG)

**Comment by denis-gvardionov** [comment]
@atirtahirgroupdocs 

I reviewed and investigated the attached solution in details. It was reported that the project cannot be build successfully and I was asked to take a look. Here's my review.

1. Attached project named "WebApplication5" is really uncompilable and thus cannot be launched due to several reasons, see below.
2. First of all, it contains a set of references to really huge amount of libraries through NuGet links. It uses all existing Aspose libraries, as well as GroupDocs.Viewer and a GroupDocs.Editor ver 21.1.1 (which one is obsolete, just to mention). In order to launch the project you need to restore them all, which will require approximately of 6 GiB of free space on a system drive and a some time to download them all.
3. CSPROJ project file contains references to the files Default.aspx and Editor.aspx, which are actually missing in the project folder, so you need to remove references to these missing files manually from the Solution explorer in MS Visual Studio (or manually in the CSPROJ).
4. And the most difficult one: the method "GetValue" in the file "CacheExtensions", that is used in context of GroupDocs.Viewer, is not compilable, because there is a conflict between System.Func from mscorlib (BCL) and System.Func from GroupDocs.Editor for .NET. In order to solve this conflict you need to involve an "extern alias" mechanism. However it cannot be easily done because mscorlib is referenced implicitly and cannot be found in the Solution explorer. So you need to manually edit the "WebApplication5.csproj" file, add a mscorlib with desired alias there, and then use this alias in the "CacheExtensions.cs" file.
5. After these manipulations the project will become a compilable and successfully runnable.
6. Next, despite the "GroupDocs.Editor for .NET WebForms Example" origin, the provided project lacks the "client" folder, that contains the source code of an Angular WYSIWYG editor. And if we simply copy the "https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET/tree/master/Demos/WebForms/src/client" folder into the root folder of a "WebApplication5" project, the same error, as in the attached screenshot, will occur. Also, the "WebApplication5" lacks the "https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET/tree/master/Demos/WebForms/src/Resources" folder, which normally should be filled with scripts during project build.
7. Why this issue occurs and how to fix it - hard to say, because it is area of Angular settings, not ASP.NET and/or GroupDocs.Editor-related, and I recommend to contact the developer of a "GroupDocs.Editor for .NET WebForms Example" for the further advices regarding Angular. Problem of this attached project is not inside the GroupDocs.Editor for .NET DLL, as I can see from above.

**Comment by kalikiatkiat** [comment]
Dear Denis,

I was on the vacation on the past week.
Thanks for your detailed response.
Let me discuss with my team and see how to solve it.

Regards,
WK
